# Site
name: 'Ata Gowani's Blog'
title: 'Ata Gowani's Blog'
description: 'This is Ata's blog for all thoughts tech, religion, theology, and more.''
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ata:
    name: Ata Gowani
    display_name: Ata Gowani
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: me@atagowani.com
    web: https://atagowani.com
    # twitter: 
    description: "A software engineer interested in privacy and security."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to 'enabled' to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: 'disabled'
adsense-data-ad-client: ''
adsense-data-ad-slot: ''

# Lazy Images ('enabled' or 'disabled')
lazyimages: 'enabled'

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
